// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/user.proto

package greeter

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _user_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CallRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CallRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	return nil
}

// CallRequestValidationError is the validation error returned by
// CallRequest.Validate if the designated constraints aren't met.
type CallRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallRequestValidationError) ErrorName() string { return "CallRequestValidationError" }

// Error satisfies the builtin error interface
func (e CallRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallRequestValidationError{}

// Validate checks the field values on CallResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CallResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Message

	return nil
}

// CallResponseValidationError is the validation error returned by
// CallResponse.Validate if the designated constraints aren't met.
type CallResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CallResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CallResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CallResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CallResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CallResponseValidationError) ErrorName() string { return "CallResponseValidationError" }

// Error satisfies the builtin error interface
func (e CallResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCallResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CallResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CallResponseValidationError{}
